### PR TITLE
Stretch has moved to archive.debian.org

### PR DESCRIPTION
**Pull request by MalteJ**

### CODE REVIEW

**Comment by nasbdh9** [comment]
After updating the link and re creating, there is still a 404 error, as if it has not taken effect, @mshych can you take a look

**Comment by ehdoyle** [comment]
Hi - @mshych just pointed this out to me. Turns out it's a bigger fix than just updating the one file since a broken Debian 9 image breaks the debian-package template (used, as one would expect) to build packages for Debian 9 and ONIE, and up to this point DUE has assumed it would be using containers that worked when it pulled them - which started to fall apart with a key expiration for Debian 8 containers that needed a workaround.
The real fix would be an updated stretch 9 container, but since support for older distributions is unlikely to be prompt,  I'm pushing a set of fixes that will patch the sources list before the template code (ONIE or debian-package) tries to use it. To try this out:
cd DUE
git pull --rebase     << grab the latest code
./due --create --clean   << get rid of any old build areas that might be cached
./due --create --platform linux/amd64    --name onie-build-debian-9     --prompt ONIE-9   --tag onie   --use-template onie     --from debian:9   --description "ONIE Build Debian 9" --image-patch debian/9/filesystem

the --image-patch should apply the updated file to fix this
That should (or at least it worked for me) create the container.
Let me know how it goes. If things seem to be working I'll tidy a few other things up and publish a new release.

**Comment by nasbdh9** [comment]
Confirmed that Debian 9 containers can be created after updating to ffc9607

**Comment by ehdoyle** [comment]
I'm going to close this out. The contents of the pull request were accepted (thanks!) but fixing the issue of older containers having stale information turned out to be a bit more complex.  The current source version of DUE recommends building any Debian 9 container (for package build or ONIE ) with the 
--image-patch debian/9/filesystem
option.

**Pull request closed without merging**
